import { fileURLToPath } from "url";
import { dirname } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Explicit semantic replacements for historic URLs verified as 404 or redirecting to 404.
// Administrative probes (for example /cpanel) are intentionally excluded.
const legacyRedirectMappings = [
  ["/2014/12/11/blood-clots-travel-advise-information/", "/services/vein-disorders"],
  ["/2014/12/17/causes-spider-veins/", "/services/spider-vein-treatment"],
  ["/2014/12/26/varicose-veins-vein-valves/", "/services/varicose-vein-treatment"],
  ["/2015/03/10/bleeding-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2015/06/08/family-history-prevention-varicose-veins-even-possible/", "/services/varicose-vein-treatment"],
  ["/2016/11/25/understanding-leg-veins/", "/blog"],
  ["/2017/05/25/leg-vein-treatment-facts-answer-questions/", "/blog"],
  ["/2017/12/29/varicose-veins-now-emergency-situations/", "/services/varicose-vein-treatment"],
  ["/2018/01/12/pregnancy-effects-leg-veins/", "/blog"],
  ["/2018/01/26/leg-vein-treatment-pregnant-call-leg-vein-non-treatment-pregnancy/", "/blog"],
  ["/2018/02/13/winter-weather-effect-leg-veins/", "/blog"],
  ["/2018/02/27/complications-leg-veins-left-untreated/", "/blog"],
  ["/2018/10/09/three-signs-you-really-need-to-see-a-vein-specialist-in-new-york/", "/blog"],
  ["/2018/10/19/three-signs-you-really-need-to-see-a-vein-specialist-in-new-york-2/", "/blog"],
  ["/2018/10/29/three-signs-you-really-need-to-see-a-vein-specialist-in-new-york-3/", "/blog"],
  ["/2019/01/22/a-new-year-a-new-set-of-vein-free-legs-or-hands-temples-breasts-or-chest/", "/services/body-vein-treatment"],
  ["/2020/02/05/family-history-and-the-prevention-of-varicose-veins-is-it-even-possible/", "/services/varicose-vein-treatment"],
  ["/2020/02/12/how-to-treat-a-venous-leg-ulcer-doctors-guide/", "/services/vein-disorders"],
  ["/2020/02/24/the-best-cosmetic-surgery-for-spider-veins/", "/services/spider-vein-treatment"],
  ["/2020/03/15/varicose-veins-why-not-them-is-deadly/", "/services/varicose-vein-treatment"],
  ["/2020/03/25/walking-around-long-island-is-painful-for-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2020/04/09/why-summer-makes-varicose-vein-symptoms-worse/", "/services/varicose-vein-treatment"],
  ["/2020/04/20/what-causes-lymphedema/", "/services/vein-disorders"],
  ["/2020/05/11/what-you-can-do-about-venous-ulcers/", "/services/vein-disorders"],
  ["/2020/05/25/how-summer-heat-affects-your-veins/", "/blog"],
  ["/2020/06/13/get-compression-stockings-fitted-to-your-legs/", "/blog"],
  ["/2020/06/24/pregnant-and-starting-to-get-pelvic-varicose-veins/", "/services/body-vein-treatment"],
  ["/2020/07/08/get-rid-of-spider-veins-on-your-face/", "/services/spider-vein-treatment"],
  ["/2020/07/25/a-guide-to-the-bulging-veins-on-your-hands/", "/services/body-vein-treatment"],
  ["/2020/08/05/is-varicose-vein-treatment-safe-and-effective/", "/services/varicose-vein-treatment"],
  ["/2020/08/21/why-autumn-is-the-ideal-time-for-vein-treatments/", "/blog"],
  ["/2020/08/23/tanning-spray-tanning-are-bad-for-spider-veins-and-the-body/", "/services/spider-vein-treatment"],
  ["/2020/09/08/varicose-veins-wont-bring-katy-perrys-positive-spirit-down/", "/services/varicose-vein-treatment"],
  ["/2020/09/21/why-autumn-is-the-ideal-time-for-vein-treatments/", "/blog"],
  ["/2020/10/05/steps-to-treat-varicose-vein-eczema-and-the-itchy-symptoms/", "/services/vein-disorders"],
  ["/2020/10/23/diabetes-varicose-veins-and-sugar-filled-halloween-candy/", "/services/varicose-vein-treatment"],
  ["/2020/11/02/tomatoes-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2020/11/22/does-cbd-oil-help-minimize-the-size-of-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2020/12/02/how-to-care-for-your-varicose-veins-in-the-winter/", "/services/varicose-vein-treatment"],
  ["/2020/12/17/indoor-exercises-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/01/11/signs-of-deep-vein-thrombosis/", "/services/vein-disorders"],
  ["/2021/01/21/varicose-veins-get-worse-during-winter/", "/services/varicose-vein-treatment"],
  ["/2021/02/11/will-insurance-pay-for-varicose-vein-treatment/", "/services/varicose-vein-treatment"],
  ["/2021/02/21/facial-redness-spider-veins-and-professional-advice/", "/services/spider-vein-treatment"],
  ["/2021/03/04/worried-you-have-deep-vein-thrombosis-symptoms-checker/", "/services/vein-disorders"],
  ["/2021/03/24/how-to-get-rid-of-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/04/05/treat-your-spider-veins-manhattan/", "/services/spider-vein-treatment"],
  ["/2021/04/24/get-a-cosmetic-vein-treatment-now-or-later/", "/blog"],
  ["/2021/05/11/marijuana-cause-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/05/22/does-ocean-water-help-cure-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/06/12/do-varicose-vein-creams-and-vitamins-work/", "/services/varicose-vein-treatment"],
  ["/2021/06/18/when-to-treat-spider-veins-before-your-wedding/", "/services/spider-vein-treatment"],
  ["/2021/07/05/outdoor-recreational-exercises-that-help-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/07/18/visiting-a-vein-doctor-after-getting-your-covid-19-vaccine/", "/blog"],
  ["/2021/08/11/how-pregnancy-causes-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/08/25/phlebologist-vs-dermatologist-who-is-better-at-treating-leg-veins/", "/blog"],
  ["/2021/09/12/dvt-pulmonary-embolisms-and-your-life-at-risk/", "/services/vein-disorders"],
  ["/2021/09/20/phlebologists-treating-leg-veins/", "/blog"],
  ["/2021/10/01/leg-vein-treatment-surgery-options-for-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2021/10/15/everything-you-need-to-know-about-blood-thinners-dvt/", "/services/vein-disorders"],
  ["/2021/11/11/benefits-uses-of-compression-stockings-for-dvt/", "/services/vein-disorders"],
  ["/2021/11/25/the-effects-of-birth-control-on-vein-appearance/", "/blog"],
  ["/2021/12/11/winter-leg-vein-treatments/", "/blog"],
  ["/2021/12/22/improve-your-quality-of-life-with-leg-vein-treatment/", "/blog"],
  ["/2022/05/18/why-do-women-get-more-varicose-and-spider-vein-treatment-than-men/", "/services/spider-vein-treatment"],
  ["/2022/08/08/foam-sclerotherapy-for-leg-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2023/03/25/summer-is-coming/", "/blog"],
  ["/2023/11/25/exercise-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/2023/12/03/connection-between-varicose-veins-and-pregnancy/", "/services/varicose-vein-treatment"],
  ["/2023/12/10/laser-vein-removal-for-varicose-veins/", "/services/laser-vein-therapy"],
  ["/2023/12/17/guide-to-varicose-vein-prevention/", "/services/varicose-vein-treatment"],
  ["/Hand-Arm-treatment.htm", "/services/body-vein-treatment"],
  ["/about-phlebology/", "/about"],
  ["/about-the-doctors/", "/about"],
  ["/about-vein-care/", "/about"],
  ["/about.html", "/about"],
  ["/aboutVeinCenter.htm", "/about"],
  ["/before-after/", "/results"],
  ["/before-and-after/", "/results"],
  ["/bleeding-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/category/deep-vein-thrombosis/", "/services/vein-disorders"],
  ["/category/health-insurance/", "/services/free-vein-screening"],
  ["/category/new-york-vein-doctor-blog/", "/blog"],
  ["/category/patient-resources/", "/blog"],
  ["/category/spider-vein-treatment/", "/services/spider-vein-treatment"],
  ["/category/spider-vein-treatment/page/2/", "/services/spider-vein-treatment"],
  ["/category/spider-veins/", "/services/spider-vein-treatment"],
  ["/category/spider-veins/page/2/", "/services/spider-vein-treatment"],
  ["/category/treatment/", "/blog"],
  ["/category/treatment/page/2/", "/blog"],
  ["/category/uncategorized/", "/blog"],
  ["/category/uncategorized/page/2/", "/blog"],
  ["/category/varicose-veins/", "/services/varicose-vein-treatment"],
  ["/category/varicose-veins/page/2/", "/services/varicose-vein-treatment"],
  ["/causes-spider-veins/", "/services/spider-vein-treatment"],
  ["/certification/", "/about"],
  ["/compression-stockings/", "/services/vein-disorders"],
  ["/contact.html", "/contact"],
  ["/contact/commack-long-island-vein-treatment/", "/locations/commack"],
  ["/contact/long-island-manhasset/", "/locations/manhasset"],
  ["/contact/manhattan-vein-treatment/", "/locations/manhattan"],
  ["/covid-19/", "/blog"],
  ["/endo-venous-laser-therapy-evlt/", "/services/laser-vein-therapy"],
  ["/facial-varicose-vein-treatment/", "/services/spider-vein-treatment"],
  ["/family-history-prevention-varicose-veins-even-possible/", "/services/varicose-vein-treatment"],
  ["/faqs-about-svlc-vein-therapy/", "/faq"],
  ["/faqs-about-veins/", "/faq"],
  ["/faqs-schulman-vein-laser-center/", "/faq"],
  ["/glossary-terms/", "/services/vein-disorders"],
  ["/handarm.html", "/services/body-vein-treatment"],
  ["/how-to-prevent-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/index.htm", "/"],
  ["/index.html", "/"],
  ["/index3.htm", "/"],
  ["/insurance-coverage-for-vein-treatments/", "/services/free-vein-screening"],
  ["/insurance-coverage/", "/services/free-vein-screening"],
  ["/lasertreatment.htm", "/services/laser-vein-therapy"],
  ["/lecturecv.html", "/about"],
  ["/leg-swelling-two-potential-ways-help/", "/services/vein-disorders"],
  ["/legVeinTreatment.htm", "/services/varicose-vein-treatment"],
  ["/legvein.html", "/services/varicose-vein-treatment"],
  ["/long-island-commack/", "/locations/commack"],
  ["/long-island-manhasset/", "/locations/manhasset"],
  ["/manhattan-new-york/", "/locations/manhattan"],
  ["/meet-doctors-2/", "/about"],
  ["/other-body-veins/", "/services/body-vein-treatment"],
  ["/otherBodyVeins.htm", "/services/body-vein-treatment"],
  ["/ourLecture.htm", "/about"],
  ["/phlebitis-of-leg-veins/", "/services/vein-disorders"],
  ["/phlebitis/", "/services/vein-disorders"],
  ["/photos.htm", "/results"],
  ["/photos.html", "/results"],
  ["/pregnancy-and-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/project/breast-vein-removal-after-breast-lift-surgery/", "/results"],
  ["/project/breast-veins-2/", "/results"],
  ["/project/breast-veins-patient-2/", "/results"],
  ["/project/breast-veins/", "/results"],
  ["/project/enlarged-hand-veins/", "/results"],
  ["/project/enlarged-varicose-veins/", "/results"],
  ["/project/hand-veins-2/", "/results"],
  ["/project/hand-veins-3/", "/results"],
  ["/project/hand-veins-patient-2/", "/results"],
  ["/project/hand-veins-patient-3/", "/results"],
  ["/project/hand-veins/", "/results"],
  ["/project/spider-veins-1/", "/results"],
  ["/project/spider-veins-2/", "/results"],
  ["/project/spider-veins-3/", "/results"],
  ["/project/spider-veins-4/", "/results"],
  ["/project/spider-veins-5/", "/results"],
  ["/project/spider-veins-6/", "/results"],
  ["/project/spider-veins-7/", "/results"],
  ["/project/spider-veins-8/", "/results"],
  ["/project/spider-veins-9/", "/results"],
  ["/project/spider-veins-on-thigh/", "/results"],
  ["/project/spider-veins-patient-2/", "/results"],
  ["/project/spider-veins-patient-3/", "/results"],
  ["/project/spider-veins-patient-4/", "/results"],
  ["/project/spider-veins/", "/results"],
  ["/project/temple-facial-veins-2/", "/results"],
  ["/project/temple-facial-veins-patient-2/", "/results"],
  ["/project/temple-facial-veins/", "/results"],
  ["/project/temple-veins/", "/results"],
  ["/project/varicose-vein-injection-treatment/", "/results"],
  ["/project/varicose-veins-patient/", "/results"],
  ["/project/varicose-veins/", "/results"],
  ["/project/varicosities-in-leg/", "/results"],
  ["/project_category/breast-veins/", "/services/body-vein-treatment"],
  ["/project_category/hand-veins/", "/services/body-vein-treatment"],
  ["/project_category/spider-veins/", "/services/spider-vein-treatment"],
  ["/project_category/spider-veins/page/2/", "/services/spider-vein-treatment"],
  ["/project_category/temple-facial-veins/", "/services/body-vein-treatment"],
  ["/project_category/varicose-veins/", "/services/varicose-vein-treatment"],
  ["/sorry.htm", "/contact"],
  ["/spider-vein-removal/", "/services/spider-vein-treatment"],
  ["/spider-vein-treatments/", "/services/spider-vein-treatment"],
  ["/spider-veins/", "/services/spider-vein-treatment"],
  ["/spiderpix.html", "/results"],
  ["/success-stories/", "/reviews"],
  ["/vaginal-varicosities/", "/services/body-vein-treatment"],
  ["/varicose-vein-treatment/", "/services/varicose-vein-treatment"],
  ["/varicose-veins-and-pregnancy/", "/services/varicose-vein-treatment"],
  ["/varicose-veins-chest-breasts/", "/services/body-vein-treatment"],
  ["/varicose-veins-vein-valves/", "/services/varicose-vein-treatment"],
  ["/varicose-veins/", "/services/varicose-vein-treatment"],
  ["/varicosepix.html", "/results"],
  ["/vein-health-treatment-blog/", "/blog"],
  ["/vein-health-treatment-blog/page/2/", "/blog"],
  ["/vein-health-treatment-blog/page/3/", "/blog"],
  ["/vein-treatments/spider-vein-treatment/", "/services/spider-vein-treatment"],
  ["/vein-treatments/varicose-vein-treatment/", "/services/varicose-vein-treatment"],
  ["/vein-treatments/vein-removal-body-veins/", "/services/body-vein-treatment"],
  ["/vein-treatments/vein-removal-body-veins/varicose-veins-in-breasts/", "/services/body-vein-treatment"],
  ["/vein-treatments/vein-removal/", "/services/body-vein-treatment"],
  ["/vein-treatments/vein-treatment/", "/services/varicose-vein-treatment"],
  ["/venous-leg-ulcers/", "/services/vein-disorders"],
  ["/venous-terminology-explained/", "/services/vein-disorders"],
  ["/what-causes-varicose-veins/", "/services/varicose-vein-treatment"],
  ["/why-schulman-vein-and-laser-center/", "/about"],
  ["/your-first-visit/", "/services/free-vein-screening"],
];

const legacyRedirects = legacyRedirectMappings.flatMap(([source, destination]) => {
  const canonicalSource = source.endsWith("/") && source !== "/" ? source.slice(0, -1) : source;
  const sources = source.endsWith("/") && source !== "/" ? [source, canonicalSource] : [source];

  return sources.map((redirectSource) => ({
    source: redirectSource,
    destination,
    permanent: true,
  }));
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  outputFileTracingRoot: __dirname,
  // Let explicit legacy trailing-slash rules issue the only redirect hop.
  skipTrailingSlashRedirect: true,
  // Compress responses
  compress: true,

  async redirects() {
    return [
      // Preserve hand-maintained blog canonicalization redirects.
      {
        source: "/blog/what-are-varicose-veins-causes-symptoms-treatment-new-york",
        destination: "/blog/varicose-vein-treatment-manhattan-new-york",
        permanent: true,
      },
      {
        source: "/blog/evlt-vs-sclerotherapy-which-treatment-is-right",
        destination: "/blog/evlt-vs-sclerotherapy-vein-treatment-new-york",
        permanent: true,
      },
      ...legacyRedirects,
    ];
  },

  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          {
            key: "Content-Security-Policy",
            value:
              "default-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'; object-src 'none'; frame-src 'self' https://www.google.com https://maps.google.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https: wss: ws:; upgrade-insecure-requests",
          },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value:
              "accelerometer=(), autoplay=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()",
          },
        ],
      },
    ];
  },

  // Aggressive image optimization
  images: {
    formats: ["image/avif", "image/webp"],
    dangerouslyAllowSVG: true,
    contentDispositionType: "inline",
    deviceSizes: [390, 640, 750, 828, 1080, 1200, 1920],
    imageSizes: [16, 32, 64, 96, 128, 256],
    minimumCacheTTL: 86400,
    remotePatterns: [],
  },

  // Faster builds + smaller bundles
  experimental: {
    optimizePackageImports: ["lucide-react", "framer-motion"],
  },
};

export default nextConfig;
